name: Build Geode Mod
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            id: android
            target: Android
            os: ubuntu-latest
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Geode SDK
        uses: geode-developers/setup-geode@v2
        with:
          target: Android

      - name: Build Mod
        run: |
          geode profile select default
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DGEODE_TARGET=${{ matrix.config.target }}
          cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.id }}-mod
          path: build/*.geode
          
