name: Build Geode Mod
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Geode CLI
        run: |
          curl -L https://github.com/geode-sdk/cli/releases/latest/download/geode-linux -o geode
          chmod +x geode
          sudo mv geode /usr/local/bin/

      - name: Build Mod
        run: |
          geode sdk setup --android
          geode package build --no-compile-check

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-mod
          path: "*.geode"
          
